spring.application.name=account_service

spring.datasource.url=${POST.URL.ACCOUNT_DB}
spring.datasource.username=${POST.USERNAME}
spring.datasource.password=${POST.PASSWORD}

spring.data.redis.host=${REDIS.HOST}
spring.data.redis.port=${REDIS.PORT}
spring.data.redis.timeout=60000

server.port=8082
