spring.application.name=auth_service

spring.datasource.url=${POST.URL.USER_DB}
spring.datasource.username=${POST.USERNAME}
spring.datasource.password=${POST.PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop

server.port=8081
