spring.application.name=transaction_service

spring.kafka.bootstrap-servers=host.docker.internal:9092
spring.kafka.consumer.group-id=transaction-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages="*"
spring.kafka.producer.properties.spring.json.type.mapping=transactionRequested:org.veedev.transactionservice.dto.TransactionRequested

server.port=8083
